### ISSUE TITLE
ElectricalGenerators mass scaling

### ISSUE THREAD

**Issue by danielguo** [sswelm/KSPInterstellar#40]
Changing the scale of ElectricalGeneratorsL and ElectricalGeneratorsS does not change its mass. When scaling these two parts, console show:

[Warning]: [TweakScale Warning] No valid member found for partMass in FNGenerator
TweakScale.Tools:LogWf(String, Object[])
TweakScale.MemberUpdater:Create(Object, String)
TweakScale.ScaleExponents:UpdateFields(Object, Object, ScalingFactor, Part)
TweakScale.ScaleExponents:UpdateObject(Part, Part, Dictionary`2, ScalingFactor)
TweakScale.TSGenericUpdater:OnRescale(ScalingFactor)
TweakScale.TweakScale:OnTweakScaleChanged()
TweakScale.TweakScale:Update()

I think it's because the part is missing partMass?

**Comment by danielguo** [comment]
Actually, the real mass seems ok, just that in the context window, the Mass still shows the same value regardless of scaling.

**Comment by sswelm** [comment]
Thank for the notification. I removed the partMass but forgot about Tweakscale was still liked.  Notice In the future, Mass will scale with reactor Power Production
