### ISSUE TITLE
Exceptions when using Squads Thermal Control Systems on Vessel

### ISSUE THREAD

**Issue by taleteller** [sswelm/KSPInterstellar#45]
I have vessels and stations using Thermal Control System for cooling. With KSPI 1.6.9 everything worked well, starting with 1.7.0 my log gets spammed with the following messages:

```
[EXC 13:30:09.475] NullReferenceException: Object reference not set to an instance of an object
    FNPlugin.FNRadiator.FixedUpdate ()
[EXC 13:30:09.475] NullReferenceException: Object reference not set to an instance of an object
    FNPlugin.FNRadiator.FixedUpdate ()
[EXC 13:30:09.488] NullReferenceException: Object reference not set to an instance of an object
    FNPlugin.FNRadiator.FixedUpdate ()
[EXC 13:30:09.488] NullReferenceException: Object reference not set to an instance of an object
    FNPlugin.FNRadiator.FixedUpdate ()
[EXC 13:30:09.504] NullReferenceException: Object reference not set to an instance of an object
    FNPlugin.FNRadiator.FixedUpdate ()
[EXC 13:30:09.504] NullReferenceException: Object reference not set to an instance of an object
    FNPlugin.FNRadiator.FixedUpdate ()
```

It even happens when no KSPI radiator is attached at all. One vessel using vanilla cooling panels also happen to experience a weird "Under Acceleration" bug during launches. I am using KSP 1.0.5 Linux x64.

**Comment by sswelm** [comment]
The problem should be fixed now

**Comment by taleteller** [comment]
Yes, I can confirm it, 1.7.4 fixed the problem. 

I had another weird encounter where flat radiators stopped removing waste heat after undocking from a regular cooled station. Might be I open another ticket if I can reproduce the issue.
